sudo: required
services:
  - docker

before_install:
  - docker build -t sarik123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sarik123/react-test npm test -- --coverage

after_success:
  - docker build -t sarik123/mult-client ./client
  - docker build -t sarik123/mult-nginx ./nginx
  - docker build -t sarik123/mult-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sarik123/mult-client
  - docker push sarik123/mult-nginx
  - docker push sarik123/mult-server

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Twitter_Sim
  env: TwitterSim-env
  bucket: elasticbeanstalk-us-east-2-893848630104
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY