version: "3.7"

services:
  # our postgres DB image
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./scripts/database-initialisation-scripts:/docker-entrypoint-initdb.d
      - ./migrations/sqls/up:/migrations
    ports:
      - "5432:5432"

